name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: Install dependencies and run tests
      - name: Install dependencies
        run: npm install

      - name: Run tests (if applicable)
        run: npm test # Optional step, modify/remove if needed

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with Buildpacks
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha[0:7] }}
            ghcr.io/${{ github.repository }}:latest
          builder: paketobuildpacks/builder:full
