name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optional: Install dependencies and run tests
      - name: Install dependencies
        run: npm install

      - name: Get short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::0:7}" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image with Buildpacks
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.short_sha }}
            ghcr.io/${{ github.repository }}:latest
          builder: paketobuildpacks/builder:full
