name: Build and Push Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: ghcr.io/${{ github.repository }}
          tag: ${{ github.sha }}
          path: '.'
          builder: 'gcr.io/paketo-buildpacks/builder:base'

      - name: Push image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Create GitHub Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const { data: deployment } = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.ref,
              required_contexts: [],
              environment: 'development',
              description: 'Deploying to development environment',
              auto_merge: false,
              transient_environment: false,
              production_environment: false,
              payload: JSON.stringify({
                image: `ghcr.io/${{ github.repository }}:${{ github.sha }}`
              })
            });
            core.setOutput('deployment_id', deployment.id);